---

  - name: Create Default Site
    template:
      src: defaultsite.conf
      dest: /etc/httpd/conf.d/defaultsite.conf
      owner: root
      group: root
      mode: 0655
    register: httpSite

  - name: HTTPd Restart
    service:
      name: httpd
      state: restarted
      enabled: yes
    when: httpSite.changed
