heat_template_version: 2015-10-15

description: |
 # For DEv only. This stack is intended for low to medium traffic 
 hybris websites and can be scaled as needed to accommodate future
 growth.  This stack will include a Cloud Load Balancer, Cloud
 Database, 2 webs, 2 hybris and 2 solrs servers.  
 It also will include Cloud Monitoring.

parameters:
  app_server_flavor:
    type: string
    default: 8 GB General Purpose v1
    label: hybris Server Flavor
    description: Flavor of Cloud Server to be used for hybris servers in this stack
    constraints:
    - allowed_values:
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
    immutable: true
  web_server_flavor:
    type: string
    default: 2 GB General Purpose v1
    label: web Server Flavor
    description: Flavor of Cloud Server to be used for web servers in this stack
    constraints:
    - allowed_values:
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
    immutable: true
  solr_server_flavor:
    type: string
    default: 2 GB General Purpose v1
    label: solr Server Flavor
    description: Flavor of Cloud Server to be used for SOLR servers in this stack
    constraints:
    - allowed_values:
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
    immutable: true
  web_server_count:
    type: number
    default: 1
    label: Number of web Servers
    description: Number of web nodes
    constraints:
      - range: { min: 0, max: 4 }
  hybris_server_count:
    type: number
    default: 1
    label: Number of hybris Servers
    description: Number of hybris nodes
    constraints:
      - range: { min: 0, max: 4 }
  solr_slaves_server_count:
    type: number
    default: 1
    label: Number of solr slave Servers
    description: Number of SOLR slaves nodes
    constraints:
      - range: { min: 0, max: 4 }

resources:
  web-servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: web_server_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          name: web-hyb-%index%
          flavor: { get_param: web_server_flavor }
          image: RAS-web-hybris
  hybris-servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: hybris_server_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          name: hybris-%index%
          flavor: { get_param: app_server_flavor }
          image: RAS-hybris63-2
  solr-master:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: OS::Nova::Server
        properties:
          name: solr-master-%index%
          flavor: { get_param: solr_server_flavor }
          image: RAS-solr-hybris
  solr-slaves:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param:  solr_slaves_server_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          name: solr-slave-%index%
          flavor: { get_param: solr_server_flavor }
          image: RAS-solr-hybris

outputs:
  web_servers_resources:
    description: WEB Servers 
    value: { get_attr:  [ web-servers, resources, networks ]  }
  hybris-servers_resources:
    description: HYBRIS Servers
    value: { get_attr: [ hybris-servers, resources, accessIPV4 ]  }
  solr-master_resources:
    description: SOLR-M Servers
    value: { get_attr: [ solr-master,  accessIPV4 ]  }
  solr-servers_resources:
    description: SOLR-S Servers
    value: { get_attr: [ hybris-servers, resources, networks, 0, address ]  }
