---
- include: configure_firewalld.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- include: configure_ufw.yml
  when: ansible_os_family == 'Debian' 

- include: configure_iptables.yml
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version < 7)
