---
- name: Create Document Root
  file:
    path: '{{ magento_document_root }}'
    state: directory
    mode: 0755

- name: Create Magento SFTP User
  user:
    name: '{{ magento_sftp_user }}'
    home: '{{ magento_document_root }}'
    password: '{{ magento_sftp_password | password_hash("sha512") }}'
    comment: '{{ magento_vhost_domain }}'

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Download Magento
  get_url:
    url: 'https://3fb66be59b12e2b636cf-d69d20d277a755fdadf91611975f2510.ssl.cf5.rackcdn.com/magento-{{ magento_version }}.tar.gz'
    dest: '{{ magento_document_root }}'
    owner: '{{ magento_sftp_user }}'
    group: '{{ nginx_vhost_user }}'
    validate_certs: no
  when: not (magento_sample_content == 'True')

- name: Download Sample Content
  get_url:
    url: "https://3fb66be59b12e2b636cf-d69d20d277a755fdadf91611975f2510.ssl.cf5.rackcdn.com/magento-sample-data-{{ magento_sample_content_version }}.tar.gz"
    dest: '{{ magento_document_root }}'
    owner: '{{ magento_sftp_user }}' 
    group: '{{ nginx_vhost_user }}'
    validate_certs: no
  when: magento_sample_content == 'True'

- name: Unpack Magento
  unarchive:
    src: '{{ magento_document_root }}/magento-{{ magento_version }}.tar.gz'
    dest: '{{ magento_document_root }}'
    copy: no
  when: not (magento_sample_content == 'True')

- name: Unpack Sample Content
  unarchive:
    src: '{{ magento_document_root }}/magento-sample-data-{{ magento_version }}.tar.gz'
    dest: '{{ magento_document_root }}'
    copy: no
  when: magento_sample_content == 'True'

- name: Configure .my.cnf
  template:
    src: 'Common/.my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: root
    group: root
    mode: 0600

- name: Delete Garbage Files
  file:
    path: '{{ magento_document_root }}/{{ item }}'
    state: absent
  with_items:
    magento_garbage_files

- name: Configure Directory Ownership and Permissions
  file:
    path: '{{ magento_document_root }}'
    owner: '{{ magento_sftp_user }}'
    group: '{{ nginx_vhost_user }}'
    mode: 0755
    state: directory
    recurse: yes

- name: Configure File Level Permissions
  command: 'find . -type f -exec chmod 644 {} ";"'
  args:
    chdir: '{{ magento_document_root }}'
  register: file_perm_change
  changed_when: file_perm_change.stdout

- name: Set Magento as executable
  file:
    path: '{{ magento_document_root }}/bin/magento'
    mode: 0500
    state: file

- name: "Run Magento setup:install"
  command: 'bin/magento setup:install --admin-firstname="{{ magento_admin_fname}}" --admin-lastname="{{ magento_admin_lname }}" --admin-email="{{ magento_admin_email }}" --admin-user="{{ magento_admin_user}}" --admin-password="{{ magento_admin_pass }}" --base-url="http://{{ magento_vhost_domain }}/" --db-host="{{ mysql_host_ip }}" --db-name="{{ magento_db_name }}" --db-user="{{ magento_db_user }}" --db-password="{{ magento_db_password }}" --session-save="{{ magento_session }}" --use-secure="1" --backend-frontname="{{ magento_admin_url }}"'
  args:
    chdir: "{{ magento_document_root }}"

- name: "Run Magento setup:static-content:deploy"
  command: 'bin/magento setup:static-content:deploy'
  args:
    chdir: "{{ magento_document_root }}"

- name: Configure File Level Permissions
  command: 'find . -type f -exec chmod 774 {} ";"'
  args:
    chdir: '{{ magento_document_root }}'
  register: file_perm_change
  changed_when: file_perm_change.stdout

- name: Configure Directory Ownership and Permissions
  file:
    path: '{{ magento_document_root }}'
    owner: '{{ magento_sftp_user }}'
    group: '{{ nginx_vhost_user }}'
    mode: 0774
    state: directory
    recurse: yes
