---
- name: Set Package Name
  set_fact:
    mysql_pkg: mysql-server
  when: mysql_pkg is not defined

- name: Install MySQL-Server
  apt:
    name: mysql-server
    state: present

- name: Install Python-MySQLDB
  apt:
    name: python-mysqldb
    state: present

- name: Load Debian Vars
  include_vars: MySQL/Debian.yml

- name: Disable AppArmor (Ubuntu)
  file:
    src: '/etc/apparmor.d/usr.sbin.mysqld'
    path: '/etc/apparmor.d/disable/usr.sbin.mysqld'
    state: link
  when: ansible_distribution == "Ubuntu"

- name: Reload AppArmor Config (Ubuntu)
  service:
    name: apparmor
    state: reloaded
  when: ansible_distribution == "Ubuntu"
