---
- name: Install python-selinux
  apt:
    name: python-selinux
    state: present

- name: Install Vim
  apt:
    name: vim
    state: present

- name: Install NTPD
  apt:
    name: ntp
    state: present

- name: Set NTP Service Fact
  set_fact:
    ntp_service: ntpd
