---
- name: Create /etc/gitlab/gitlab.rb
  template:
    src: 'Common/gitlab.rb.j2'
    dest: '/etc/gitlab/gitlab.rb'

- name: Ensure '/var/opt/gitlab/nginx/conf' directory exists
  file:
    path: '/var/opt/gitlab/nginx/conf/'
    state: directory

- name: Set up Nginx redirect
  template:
    src: 'Common/gitlab-http-redirect.conf.j2'
    dest: '/var/opt/gitlab/nginx/conf/gitlab-http-redirect.conf'

- name: Configure GitLab
  command:
    'gitlab-ctl reconfigure'

- name: Configure Backups
  cron:
    job: 'gitlab-rake gitlab:backup:create'
    minute: '0'
    hour: '0'
    name: 'GitLab Backup'
    state: present
