---
- name: Include Debian Vars
  include_vars: Debian.yaml

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
  - curl
  - openssh-server
  - ca-certificates
  - postfix
  - apt-transport-https

- name: Add GitLab Repository
  apt_repository:
    repo: 'deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ trusty main'
    state: present

- name: Install GitLab
  apt:
    name: gitlab-ce
    state: present
    force: yes
